-- 全量价格库导入
TRUNCATE price_catalog;

INSERT INTO price_catalog (country, name, cert_type, sample_qty, based_on_report, lead_weeks, includes_testing, cert_validity_years, series_apply, ref_price, remark) VALUES
('Abu Dhabi', 'TDRA', '强制', NULL, 'Y', 5, 'Y', 3, 'N', 4500, NULL),
('Afghanistan', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Albania', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Algeria', 'ARPCE', '强制', 1, NULL, 12, 'Y', 2, 'N', 22500, NULL),
('Am. Oceania', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Andorra', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Angola', 'INACOM', '强制', NULL, NULL, 5, 'Y', 1, 'N', 8800, NULL),
('Antigua & Barbuda', 'MBT', '强制', NULL, NULL, 5, 'Y', NULL, 'N', 7500, NULL),
('Argentina', 'ENACOM', '不强制', NULL, '当地测试', 10, 'Y', 3, 'N', 24800, '1pcs传导定频样机，1pcs正常样机'),
('Armenia', 'AR CoC (RF)', '强制', NULL, '基于CE', 3, 'Y', 1, 'N', 16000, NULL),
('Aruba', 'DTA', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 7800, NULL),
('Australia', 'RCM', '强制', NULL, '基于CE', 2, 'Y', NULL, 'Y', 1500, NULL),
('Austria', 'CE', '强制', NULL, '基于CE', NULL, NULL, NULL, NULL, NULL, NULL),
('Azerbaijan', 'AZ Mincom CoC (RF)', '强制', NULL, '基于CE', 3, 'Y', 1, 'N', 15000, NULL),
('Bahamas', 'URCA', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 6800, NULL),
('Bahrain', 'TRA', '强制', NULL, '基于CE', 2, 'Y', 3, 'N', 5000, NULL),
('Bangladesh', 'BTRC', '不强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Barbados', 'BTU', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 5500, NULL),
('Belarus', 'BY TR DoC (RF)', '强制', 1, '基于CE', 5, 'Y', 5, 'N', 9000, '1pcs传导定频样机'),
('Belgium', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Belize', 'PUC', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 10000, NULL),
('Benin', 'ARCEP', '强制', NULL, '基于CE', 8, 'Y', 5, 'N', 11500, '1pcs正常样机'),
('Bermuda', 'DOT', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 8000, NULL),
('Bhutan', 'Bhutan', '不强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Bolivia', 'ATT', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 5500, NULL),
('Bosnia and Herzegovina', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Botswana', 'BOCRA', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 7600, NULL),
('Brazil', 'Anatel', '强制', NULL, '当地测试', 10, 'Y', NULL, 'N', 48000, '1pcs传导定频样机，1pcs正常样机'),
('Brunei Darussalam', 'AITI', '强制', NULL, '基于CE', 2, 'Y', 5, 'N', 5500, NULL),
('Bulgaria', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Burkina Faso', 'ARCEP', '强制', NULL, '基于CE', 4, 'Y', 5, 'N', 8000, NULL),
('Burundi', 'ARCT', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 10500, '1pcs正常样机'),
('Cambodia', 'TRC', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 15000, NULL),
('Cameroon', 'ART', '强制', NULL, '基于CE', 12, 'Y', NULL, 'N', 15000, NULL),
('Cabo Verde', 'ARME', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 6800, NULL),
('Cayman Islands', 'OFREG', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 8900, NULL),
('Central African Republic', 'ART', '强制', NULL, '基于CE', 8, 'Y', 5, 'N', 14000, NULL),
('Chad', 'ARCEP', '强制', NULL, '基于CE', 5, 'Y', 5, 'N', 9500, '1pcs正常样机'),
('Chile', 'SUBTEL', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 4800, NULL),
('China, People''s Republic of', 'CCC SRRC', '强制', NULL, '当地测试', NULL, NULL, NULL, NULL, NULL, NULL),
('Christmas Island', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Cocos (Keeling) Islands', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Cook Islands', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Colombia', 'CRC', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 4800, NULL),
('Comoros', 'ANRTIC', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 10000, NULL),
('Congo, Democratic Republic of', 'ARPTC', '强制', NULL, '基于CE', 5, 'Y', 2, 'N', 12000, NULL),
('Congo, Republic of', 'ARPCE', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 12000, NULL),
('Coral Sea Islands', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Costa Rica', 'SUTEL', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 4800, NULL),
('Côte d''Ivoire', 'ARTCI', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 6500, '1pcs正常样机'),
('Croatia', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Cuba', 'MIC', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', NULL, NULL),
('Curaçao', 'BT&P', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 7000, NULL),
('Cyprus', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Czech Republic', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Denmark', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Djibouti', 'MCCPT', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 12000, NULL),
('Dominica', 'NTRC', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 7500, NULL),
('Dominican Republic', 'INDOTEL', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 7500, NULL),
('Dubai', 'TDRA+ROHS', '强制', NULL, '基于CE', NULL, NULL, NULL, NULL, NULL, NULL),
('East Timor', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Ecuador', 'ARCOTEL', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 4800, NULL),
('Egypt', 'NTRA', '强制', NULL, '基于CE', NULL, NULL, NULL, NULL, NULL, 'SGS,SMQ,贝科，泰尔'),
('El Salvador', 'SIGET', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 6500, NULL),
('Equatorial Guinea', 'ORTEL', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 13000, NULL),
('Eritrea', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Estonia', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Ethiopia', 'ECA', '强制', NULL, '基于CE', 6, 'Y', 2, 'N', 7800, NULL),
('Eurasian Customs Union', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('European Union', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Faeroer', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Falkland Islands', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Fiji', 'TAF', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 10000, NULL),
('Finland', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('France', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Guyana', 'PUC', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 5500, NULL),
('French Polynesia', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Gabon', 'ARCEP', '强制', NULL, '基于CE', 6, 'Y', 2, 'N', 12500, NULL),
('Gambia', 'PURA', '强制', NULL, '基于CE', 6, 'Y', 2, 'N', 8500, NULL),
('Gaza Strip', 'MTIT', '强制', NULL, '基于CE', 6, 'Y', 3, 'N', 10500, NULL),
('Georgia', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Germany', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Germany (Import)', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Ghana', 'NCA', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 13000, '1pcs正常样机'),
('Gibraltar', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Greece', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Greenland', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Grenada', 'NTRC', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 9200, NULL),
('Guadeloupe', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Guatemala', 'SIT', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 7500, NULL),
('Guinea', 'ARPT', '强制', NULL, '基于CE', 8, 'Y', 5, 'N', 18800, '1pcs正常样机'),
('Guinea-Bissau', 'ARN / ICGB', '强制', NULL, '基于CE', 8, 'Y', 5, 'N', 12000, '1pcs正常样机'),
('Guyana', 'PUC', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 6800, NULL),
('Haiti', 'CONATEL', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 18000, '1pcs正常样机'),
('Heard Island and McDonald Islands', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Honduras', 'CONATEL', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 14000, '1pcs正常样机'),
('Hong Kong', 'OFCA', '不强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 19000, NULL),
('Hungary', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Iceland', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('India', 'WPC', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 4000, NULL),
('Indonesia', 'SDPPI', '强制', NULL, '当地测试', 8, 'Y', 3, 'N', 32000, '1pcs传导定频样机，1pcs正常样机'),
('Iran', 'CRA', '强制', NULL, '基于CE', 8, 'Y', 3, 'N', 23000, '1pcs正常样机'),
('Iraq', 'CMC', '强制', NULL, '基于CE', 2, 'Y', 1, 'N', 6800, NULL),
('Ireland', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Israel', 'MOC', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 8800, NULL),
('Italy', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jamaica', 'SPECTRUM', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 8300, NULL),
('Japan', 'MIC', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jordan', 'TRC', '强制', NULL, '基于CE', 3, 'Y', 1, 'N', 7500, NULL),
('Kanarische Inseln', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kazakhstan', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kenya', 'CCK /ANRT', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 8800, NULL),
('Kiribati', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Korea, Democratic Republic of', 'KC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Korea, Republic of', 'KC', '强制', NULL, '当地测试', 2, 'Y', NULL, 'N', 65000, '1pcs传导定频样机，1pcs正常样机'),
('Kosovo', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kuwait', 'CITRA', '强制', NULL, '基于CE', 4, 'Y', 3, 'N', 7500, NULL),
('Kyrgyzstan', 'KG CoC (RF)', '强制', NULL, '基于CE', 2, 'Y', 1, 'N', 14000, NULL),
('Laos', 'MPT', '强制', NULL, '基于CE', 4, 'Y', 1, 'N', 9500, NULL),
('Latvia', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Lebanon', 'TRA', '强制', NULL, '基于CE', 10, 'Y', NULL, 'N', 7500, NULL),
('Lesotho', 'LCA', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 9500, NULL),
('Liberia', 'LTA', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 11500, NULL),
('Libya', 'CIM', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 11500, NULL),
('Lichtenstein', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Lithuania', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Luxembourg', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Macau', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Macedonia', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Madagascar', 'ARTEC', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 7500, NULL),
('Malawi', 'MACRA', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 9500, NULL),
('Malaysia', 'SIRIM', '强制', NULL, '基于CE', 4, 'Y', 5, 'N', 18000, NULL),
('Maldives', 'MCA', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 7500, NULL),
('Mali', 'AMRTP', '强制', NULL, '基于CE', 8, 'Y', 5, 'N', 7500, NULL),
('Malta', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Marshallislands', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Martinique', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Mauritania', 'ARE', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 10500, NULL),
('Mauritius', 'ICTA', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 10500, NULL),
('Mayotte', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Mexico', 'NOM', '强制', NULL, '当地测试', 8, 'Y', 1, 'N', 48000, '1pcs传导定频样机，1pcs正常样机'),
('Micronesia', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Moldova', 'SM TEC+DoC (RF)', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 12000, NULL),
('Monaco', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Mongolia', 'CRC', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 5800, NULL),
('Montenegro', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Montserrat', 'ICA', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 7800, NULL),
('Morocco', 'ANRT', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 5500, NULL),
('Mozambique', 'INCM', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 8800, NULL),
('Myanmar', 'PTD', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 12000, NULL),
('Namibia', 'CRAN', '强制', NULL, '基于CE', 6, 'Y', 3, 'N', 10000, NULL),
('Nauru', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Nepal', 'NTA', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 12000, '新申请 7000，更新5000'),
('Netherlands', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('New Caledonia', 'NA', '强制', NULL, '基于CE', 8, 'Y', 3, 'N', 14000, NULL),
('New Zealand', 'RCM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Newseal. Oceania', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Nicaragua', 'TELCOR', '强制', NULL, '基于CE', 10, 'Y', NULL, 'N', 7800, NULL),
('Niger', 'ARTP', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 10500, NULL),
('Nigeria', 'NCC', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 23000, NULL),
('Northern Cyprus', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Norway', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Oman', 'TRA', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 5800, NULL),
('Pakistan', 'PTA', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 9800, NULL),
('Panama', 'ASEP', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 8600, NULL),
('Panama-Canal', 'ASEP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Papua New Guinea', 'RCM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Paraguay', 'CONATEL', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 14000, NULL),
('Peru', 'MTC', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 5500, NULL),
('Philippines', 'NTC', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 5000, NULL),
('Pitcairn Islands', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Poland', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Portugal', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Azores', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Madeira', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Puerto Rico', 'CE ，FCC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Qatar', 'CRA', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 5800, NULL),
('Reunion', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Romania', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Russian Federation', 'EAC +FAC', '强制', NULL, '基于CE', 6, 'Y', 5, 'N', 23000, NULL),
('Rwanda', 'RURA', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 8800, NULL),
('Saba, Bonaire, Sint Eustatius', 'Agentschap Telecom', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 7800, NULL),
('Solomon Islands', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Samoa', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Sao Thome and Principe', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Saudi Arabia', 'CITC', '不强制', NULL, '基于CE', 4, 'Y', 2, 'N', 5500, NULL),
('Senegal', 'ARTP', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 12000, NULL),
('Serbia', 'KVALITET  RF', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 7000, NULL),
('Seychelles', 'DICT', '强制', NULL, '基于CE', 4, 'Y', NULL, 'N', 7500, NULL),
('Sierra Leone', 'NATCOM', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 11600, NULL),
('Singapore', 'IMDA', '强制', NULL, '基于CE', 2, 'Y', 5, 'N', 4200, NULL),
('Slovakia', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Slovenia', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Somalia', 'NCA', '强制', NULL, '基于CE', 10, 'Y', 3, 'N', 8600, NULL),
('South Africa, Republic of', 'ICASA', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 7800, NULL),
('Spain', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Ceuta', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Melilla', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('San Marino', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Sint Maarten (Dutch Part)', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Sri Lanka', 'TRC', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 6000, NULL),
('St. Barts', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('St. Helena', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('St. Kitts & Nevis', 'FCC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('St. Lucia', 'CNTR', '强制', NULL, '基于CE', 7, 'Y', 10, 'N', 9800, NULL),
('St. Martin (French Part)', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('St. Pierre and Miquelon', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('St. Vincent', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Sudan', 'NCA', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 7200, NULL),
('Suriname', 'TAS', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 7500, NULL),
('Swaziland', 'SSCOM / SCCOM', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 10000, NULL),
('Sweden', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Switzerland', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Syria', 'SY-TPRA', '强制', NULL, '基于CE', 6, 'Y', 3, 'N', 8600, NULL),
('Taiwan', 'NCC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Tajikistan', 'TJ CoC (Safety, EMC, RF)', '强制', NULL, '基于CE', 6, 'Y', 1, 'N', 16000, NULL),
('Tanzania', 'TCRA', '强制', NULL, '基于CE', 3, 'Y', NULL, 'N', 11000, NULL),
('Thailand', 'NBTC SDOC', '强制', NULL, '基于CE', 2, 'Y', NULL, 'N', 3200, NULL),
('Togo', 'ARTP', '强制', NULL, '基于CE', 8, 'Y', 5, 'N', 14000, NULL),
('Tonga', 'TCC', '强制', NULL, '基于CE', 8, 'Y', 5, 'N', 13000, NULL),
('Trinidad and Tobago', 'TATT', '强制', NULL, '基于CE', 5, 'Y', 5, 'N', 8200, NULL),
('Tunisia', 'CERT & ANCE', '强制', NULL, '基于CE', 8, 'Y', NULL, 'N', 15000, '1个正常样机'),
('Turkey', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Turkmenistan', 'TDS CoC (Safety, EMC, RF)', '强制', NULL, '基于CE', 3, 'Y', 1, 'N', 15000, NULL),
('Turks- and Caicosisland', 'TCITC', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 15000, NULL),
('Tuvalu', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Uganda', 'UCC', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 10000, NULL),
('Ukraine', 'UA TR TEC + UA TR DoC (RF)', '强制', NULL, '基于CE', 5, 'Y', NULL, 'N', 15000, NULL),
('United Arab Emirates', 'TDRA', '强制', NULL, '基于CE', 5, 'Y', 3, 'N', 4500, NULL),
('United Kingdom', 'UKCA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('United States of America', 'UL，FCC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('United States of America (CKD)', 'UL，FCC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('American Virgin Islands', 'UL，FCC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Uruguay', 'URSEC', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 7800, NULL),
('Uzbekistan', 'STZ CoC (Safety, RF)', '强制', NULL, '基于CE', 6, 'Y', 1, 'N', 13000, NULL),
('Vanuatu', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Vatikan', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Venezuela', 'CONATEL', '强制', NULL, '基于CE', 10, 'Y', NULL, 'N', 7500, NULL),
('Vietnam', 'MIC', '强制
小于60mW豁免', NULL, '当地测试', 8, 'Y', 1, 'N', 15000, '1pcs传导定频样机，1pcs正常样机
小于60mW豁免'),
('British Virgin Islands', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Wallis/Futuna', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('West Bank', 'MTIT', '强制', NULL, '基于CE', 6, 'Y', 3, 'N', 10000, NULL),
('Western Sahara', 'CE', '强制', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Yemen', 'MTIT', '强制', NULL, '基于CE', 6, 'Y', 1, 'N', 15000, NULL),
('Zambia', 'ZICTA', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 8600, NULL),
('Zimbabwe', 'POTRAZ', '强制', NULL, '基于CE', 6, 'Y', NULL, 'N', 11000, NULL);
